# Generated by Django 6.0.5 on 2026-05-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservice',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.professionalprofile'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_services', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='requests', to='services.serviceimage'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['slug'], name='service_cat_slug_192b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active', 'parent'], name='service_cat_is_acti_d502ae_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalservice',
            index=models.Index(fields=['is_active', 'professional'], name='professiona_is_acti_412cd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='professionalservice',
            unique_together={('professional', 'category')},
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'created_at'], name='service_req_status_9bff2a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['city', 'state'], name='service_req_city_3ed7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['client', 'status'], name='service_req_client__c7c123_idx'),
        ),
    ]
