# Generated by Django 6.0.5 on 2026-05-14 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request', 'Quero Contratar'), ('offer', 'Quero Oferecer')], db_index=True, max_length=20)),
                ('service_name', models.CharField(help_text='Nome do serviço que você busca ou oferece', max_length=200)),
                ('description', models.TextField(help_text='Descreva o serviço em detalhes')),
                ('category_name', models.CharField(blank=True, help_text='Categoria近似 (ex: Limpeza, Reforma, Aulas) - opcional', max_length=100)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('budget', models.CharField(blank=True, help_text='Orçamento estimado (opcional)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('contacted', 'Contatado'), ('closed', 'Encerrado')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_service_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'status'], name='custom_serv_type_ee1d65_idx'), models.Index(fields=['city', 'state'], name='custom_serv_city_5c8f0b_idx'), models.Index(fields=['user', 'created_at'], name='custom_serv_user_id_9c16fd_idx')],
            },
        ),
    ]
