# Generated by Django 6.0.5 on 2026-05-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_customservicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Indica se é uma solicitação fora do catálogo'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.servicecategory'),
        ),
    ]
