# Generated by Django 6.0.5 on 2026-05-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicerequest_is_custom_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customservicerequest',
            name='custom_serv_type_ee1d65_idx',
        ),
        migrations.RemoveIndex(
            model_name='customservicerequest',
            name='custom_serv_city_5c8f0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customservicerequest',
            name='custom_serv_user_id_9c16fd_idx',
        ),
        migrations.DeleteModel(
            name='CustomServiceRequest',
        ),
    ]
