# Generated by Django 6.0.5 on 2026-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_customservicerequest_custom_serv_type_ee1d65_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(blank=True, choices=[('request', 'Quero Contratar'), ('offer', 'Quero Oferecer')], help_text='Tipo de serviço personalizado: solicitação ou oferta', max_length=20),
        ),
    ]
