# Generated by Django 6.0.5 on 2026-05-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicereview_response'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicereview',
            new_name='service_rev_profess_99239c_idx',
            old_name='service_rev_profess_idx',
        ),
        migrations.RenameIndex(
            model_name='servicereview',
            new_name='service_rev_rating_321a27_idx',
            old_name='service_rev_rating_idx',
        ),
    ]
